//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryPattern.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSharpLib.FactoryPattern.Pluralsight_FactorySample.Factory3.BMWFactory")]
        public string Factory3_BMW {
            get {
                return ((string)(this["Factory3_BMW"]));
            }
            set {
                this["Factory3_BMW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSharpLib.FactoryPattern.Pluralsight_FactorySample.Factory3.MiniCooperFactory")]
        public string Factory3_Mini {
            get {
                return ((string)(this["Factory3_Mini"]));
            }
            set {
                this["Factory3_Mini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSharpLib.FactoryPattern.Pluralsight_FactorySample.Factory4.Factory.BMWFactory")]
        public string Factory4_AutoFactory_BMW {
            get {
                return ((string)(this["Factory4_AutoFactory_BMW"]));
            }
            set {
                this["Factory4_AutoFactory_BMW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSharpLib.FactoryPattern.Pluralsight_FactorySample.Factory4.Factory.MiniCooperFac" +
            "tory")]
        public string Factory4_AutoFactory_Mini {
            get {
                return ((string)(this["Factory4_AutoFactory_Mini"]));
            }
            set {
                this["Factory4_AutoFactory_Mini"] = value;
            }
        }
    }
}
